/**:
  ros__parameters:
    general:
      grab_resolution: VGA
      pub_resolution: CUSTOM
      pub_downscale_factor: 2.0
      pub_frame_rate: 10.0

    video:
      publish_rgb: true
      publish_left_right: false
      publish_raw: false
      publish_gray: false
      publish_stereo: false

    depth:
      depth_mode: NONE
      publish_depth_map: false
      publish_depth_info: false
      publish_point_cloud: false
      publish_depth_confidence: false
      publish_disparity: false

    pos_tracking:
      pos_tracking_enabled: false
      publish_odom_pose: false
      publish_pose_cov: false
      publish_cam_path: false

    sensors:
      publish_imu: false
      publish_imu_raw: false
      publish_cam_imu_transf: false
      publish_mag: false
      publish_baro: false
      publish_temp: false
